print("Гpyna 4")
text_file = open("D:\students4.txt", "wt")
text_file.write("Ольга Степанетць 1 балів\n")
text_file.write("Илья Драгоненко 3 балів\n")
text_file.write("Дар'я Буберова 1 балів\n")
text_file.write("Любовь Губань 2 балів\n")
text_file.close()

print("Гpyna 5")
text_file = open("D:\students5.txt", "wt")
text_file.write("Инна Дубова, 0 балів\n")
text_file.write("Микола Верозуб, 3 балів\n")
text_file.write("Ольга Макаренко, 1 балів\n")
text_file.write("Маргарита Анпилогова, 2 балів\n")
text_file.close()

print("Гpyna 6")
text_file = open("D:\students6.txt", "wt")
text_file.write("Дмитро Шкробов, 2 балів\n")
text_file.write("Вікторія Муляр, 1 балів\n")
text_file.write("Дар'я Маргаза, 3 балів\n")
text_file.write("Микита Бабчій, 0 балів\n")
text_file.close()